// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/galaxy-profile/ProfilePreview.tsx": () => import("../components/mockups/galaxy-profile/ProfilePreview.tsx"),
  "./components/mockups/voice-chat/VoiceChat.tsx": () => import("../components/mockups/voice-chat/VoiceChat.tsx")
};
